-- MySQL Script generated by MySQL Workbench
-- sam. 31 oct. 2020 22:10:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tools` (
  `student_number` INT NOT NULL,
  `photoshop` VARCHAR(45) NULL,
  `illustrator` VARCHAR(45) NULL,
  `gimp` VARCHAR(45) NULL,
  `inkscape` VARCHAR(45) NULL,
  `dreamweaver` VARCHAR(45) NULL,
  `kompozer` VARCHAR(45) NULL,
  `premier` VARCHAR(45) NULL,
  `after` VARCHAR(45) NULL,
  `effect` VARCHAR(45) NULL,
  `eclipse` VARCHAR(45) NULL,
  `sublime_text` VARCHAR(45) NULL,
  `in_design` VARCHAR(45) NULL,
  `final_cut` VARCHAR(45) NULL,
  `blender` VARCHAR(45) NULL,
  `sketchup` VARCHAR(45) NULL,
  `unity` VARCHAR(45) NULL,
  `wamp` VARCHAR(45) NULL,
  `xamp` VARCHAR(45) NULL,
  `mamp` VARCHAR(45) NULL,
  `phpmyadmin` VARCHAR(45) NULL,
  `mysqlworkbench` VARCHAR(45) NULL,
  `cordova` VARCHAR(45) NULL,
  `bracket` VARCHAR(45) NULL,
  `flash` VARCHAR(45) NULL,
  `r` VARCHAR(45) NULL,
  `python` VARCHAR(45) NULL,
  `crm` VARCHAR(45) NULL,
  `slack` VARCHAR(45) NULL,
  `talent` VARCHAR(45) NULL,
  `tableau` VARCHAR(45) NULL,
  `balsamique` VARCHAR(45) NULL,
  `office` VARCHAR(45) NULL,
  `trello` VARCHAR(45) NULL,
  `gantt` VARCHAR(45) NULL,
  `latex` VARCHAR(45) NULL,
  `matlab` VARCHAR(45) NULL,
  `visual_studio` VARCHAR(45) NULL,
  `github` VARCHAR(45) NULL,
  `fillezella` VARCHAR(45) NULL,
  `ftp` VARCHAR(45) NULL,
  PRIMARY KEY (`student_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`connexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`connexion` (
  `student_number` INT NOT NULL,
  `4g` VARCHAR(45) NULL,
  `ethernet` VARCHAR(45) NULL,
  `satellite` VARCHAR(45) NULL,
  `wifi` VARCHAR(45) NULL,
  PRIMARY KEY (`student_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cms` (
  `student_number` INT NOT NULL,
  `wordpress` VARCHAR(45) NULL,
  `spip` VARCHAR(45) NULL,
  `joomla` VARCHAR(45) NULL,
  `lms` VARCHAR(45) NULL,
  `omeka_classic` VARCHAR(45) NULL,
  `omeka_s` VARCHAR(45) NULL,
  `moodel` VARCHAR(45) NULL,
  `alfresco` VARCHAR(45) NULL,
  `sharepoint` VARCHAR(45) NULL,
  `presta_shop` VARCHAR(45) NULL,
  `drupal` VARCHAR(45) NULL,
  PRIMARY KEY (`student_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`social_networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_networks` (
  `student_number` INT NOT NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `linkedin` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `whatsapp` VARCHAR(45) NULL,
  `pinterest` VARCHAR(45) NULL,
  `snapchat` VARCHAR(45) NULL,
  `discorde` VARCHAR(45) NULL,
  `telegram` VARCHAR(45) NULL,
  `gate` VARCHAR(45) NULL,
  `youtube` VARCHAR(45) NULL,
  `viadeo` VARCHAR(45) NULL,
  `vimeo` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `sky_blog` VARCHAR(45) NULL,
  `msn` VARCHAR(45) NULL,
  `blogs` VARCHAR(45) NULL,
  PRIMARY KEY (`student_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`spoken_languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spoken_languages` (
  `student_number` INT NOT NULL,
  `french` VARCHAR(45) NULL,
  `english` VARCHAR(45) NULL,
  `arabic` VARCHAR(45) NULL,
  `spanish` VARCHAR(45) NULL,
  `tamazirth` VARCHAR(45) NULL,
  `italian` VARCHAR(45) NULL,
  `portuguese` VARCHAR(45) NULL,
  `german` VARCHAR(45) NULL,
  `persian` VARCHAR(45) NULL,
  `russian` VARCHAR(45) NULL,
  `chinese` VARCHAR(45) NULL,
  `japanese` VARCHAR(45) NULL,
  PRIMARY KEY (`student_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`programming_languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`programming_languages` (
  `student_number` INT NOT NULL,
  `javascript` VARCHAR(45) NULL,
  `html` VARCHAR(45) NULL,
  `css` VARCHAR(45) NULL,
  `c` VARCHAR(45) NULL,
  `cpp` VARCHAR(45) NULL,
  `csharp` VARCHAR(45) NULL,
  `python` VARCHAR(45) NULL,
  `java` VARCHAR(45) NULL,
  `sql` VARCHAR(45) NULL,
  `lisp` VARCHAR(45) NULL,
  `smaltack` VARCHAR(45) NULL,
  `php` VARCHAR(45) NULL,
  `vb` VARCHAR(45) NULL,
  `scratch` VARCHAR(45) NULL,
  `latex` VARCHAR(45) NULL,
  `markdown` VARCHAR(45) NULL,
  `scala` VARCHAR(45) NULL,
  `csv` VARCHAR(45) NULL,
  `xml` VARCHAR(45) NULL,
  `json` VARCHAR(45) NULL,
  `rdf` VARCHAR(45) NULL,
  `owl` VARCHAR(45) NULL,
  `ml` VARCHAR(45) NULL,
  PRIMARY KEY (`student_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`needs_and_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`needs_and_skills` (
  `student_number` INT NOT NULL,
  `type` TINYINT NOT NULL,
  `web_edition` VARCHAR(45) NULL,
  `html` VARCHAR(45) NULL,
  `rwd` VARCHAR(45) NULL,
  `static_web_site` VARCHAR(45) NULL,
  `multimedia` VARCHAR(45) NULL,
  `interactive_maps` VARCHAR(45) NULL,
  `rss` VARCHAR(45) NULL,
  `metadata` VARCHAR(45) NULL,
  `sponsored_link` VARCHAR(45) NULL,
  `managing_access_tools` VARCHAR(45) NULL,
  `discussion_forum` VARCHAR(45) NULL,
  `newsletter` VARCHAR(45) NULL,
  `surveys` VARCHAR(45) NULL,
  `Information_monitoring_tools` VARCHAR(45) NULL,
  `ranking_tools` VARCHAR(45) NULL,
  `webcasting_tools` VARCHAR(45) NULL,
  `ecommerce_site` VARCHAR(45) NULL,
  `podcasts` VARCHAR(45) NULL,
  `manage_website` VARCHAR(45) NULL,
  `multilingual_site` VARCHAR(45) NULL,
  `manage_online_community` VARCHAR(45) NULL,
  `bdd_analyze` VARCHAR(45) NULL,
  `bdd_model` VARCHAR(45) NULL,
  `prototype_digital_innovations` VARCHAR(45) NULL,
  `mange_project` VARCHAR(45) NULL,
  `agile` VARCHAR(45) NULL,
  `design_ux` VARCHAR(45) NULL,
  PRIMARY KEY (`student_number`, `type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_number` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `last_formation` VARCHAR(45) NULL,
  `current_formation` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `professional_objective` VARCHAR(45) NULL,
  `specialties` VARCHAR(45) NULL,
  `computer` TINYINT NULL,
  `github` VARCHAR(45) NULL,
  `diigo` VARCHAR(45) NULL,
  `zotero` VARCHAR(45) NULL,
  `tools_student_number` INT NOT NULL,
  `connexion_student_number` INT NOT NULL,
  `cms_student_number` INT NOT NULL,
  `social_networks_student_number` INT NOT NULL,
  `spoken_languages_student_number` INT NOT NULL,
  `programming_languages_student_number` INT NOT NULL,
  `needs_and_skills_student_number` INT NOT NULL,
  `needs_and_skills_type` TINYINT NOT NULL,
  PRIMARY KEY (`student_number`, `tools_student_number`, `connexion_student_number`, `cms_student_number`, `social_networks_student_number`, `spoken_languages_student_number`, `programming_languages_student_number`, `needs_and_skills_student_number`, `needs_and_skills_type`),
  INDEX `fk_student_tools_idx` (`tools_student_number` ASC) VISIBLE,
  INDEX `fk_student_connexion1_idx` (`connexion_student_number` ASC) VISIBLE,
  INDEX `fk_student_cms1_idx` (`cms_student_number` ASC) VISIBLE,
  INDEX `fk_student_social_networks1_idx` (`social_networks_student_number` ASC) VISIBLE,
  INDEX `fk_student_spoken_languages1_idx` (`spoken_languages_student_number` ASC) VISIBLE,
  INDEX `fk_student_programming_languages1_idx` (`programming_languages_student_number` ASC) VISIBLE,
  INDEX `fk_student_needs_and_skills1_idx` (`needs_and_skills_student_number` ASC, `needs_and_skills_type` ASC) VISIBLE,
  CONSTRAINT `fk_student_tools`
    FOREIGN KEY (`tools_student_number`)
    REFERENCES `mydb`.`tools` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_connexion1`
    FOREIGN KEY (`connexion_student_number`)
    REFERENCES `mydb`.`connexion` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_cms1`
    FOREIGN KEY (`cms_student_number`)
    REFERENCES `mydb`.`cms` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_social_networks1`
    FOREIGN KEY (`social_networks_student_number`)
    REFERENCES `mydb`.`social_networks` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_spoken_languages1`
    FOREIGN KEY (`spoken_languages_student_number`)
    REFERENCES `mydb`.`spoken_languages` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_programming_languages1`
    FOREIGN KEY (`programming_languages_student_number`)
    REFERENCES `mydb`.`programming_languages` (`student_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_needs_and_skills1`
    FOREIGN KEY (`needs_and_skills_student_number` , `needs_and_skills_type`)
    REFERENCES `mydb`.`needs_and_skills` (`student_number` , `type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
