-- MySQL Script generated by MySQL Workbench
-- dim. 15 nov. 2020 23:43:27 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`diplome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diplome` (
  `iddiplome` INT NOT NULL,
  `intitule` VARCHAR(45) NULL,
  `annee` DATE NULL,
  PRIMARY KEY (`iddiplome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`social_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_network` (
  `idsocial_network` INT NOT NULL,
  `facebook` VARCHAR(45) NULL,
  `instagram` VARCHAR(45) NULL,
  `linkedin` VARCHAR(45) NULL,
  `whatsapp` VARCHAR(45) NULL,
  `youtub` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`idsocial_network`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cours` (
  `idcours` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  `professeur` VARCHAR(45) NULL,
  `periode` DATE NULL,
  PRIMARY KEY (`idcours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formation` (
  `idformation` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  `departement` VARCHAR(45) NULL,
  `cours_idcours` INT NOT NULL,
  `diplome_iddiplome` INT NOT NULL,
  PRIMARY KEY (`idformation`, `cours_idcours`, `diplome_iddiplome`),
  INDEX `fk_formation_cours1_idx` (`cours_idcours` ASC) VISIBLE,
  INDEX `fk_formation_diplome1_idx` (`diplome_iddiplome` ASC) VISIBLE,
  CONSTRAINT `fk_formation_cours1`
    FOREIGN KEY (`cours_idcours`)
    REFERENCES `mydb`.`cours` (`idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formation_diplome1`
    FOREIGN KEY (`diplome_iddiplome`)
    REFERENCES `mydb`.`diplome` (`iddiplome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `idstudent` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  `student_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `diplome_iddiplome` INT NOT NULL,
  `social_network_idsocial_network` INT NOT NULL,
  `formation_idformation` INT NOT NULL,
  `formation_cours_idcours` INT NOT NULL,
  PRIMARY KEY (`idstudent`, `diplome_iddiplome`, `social_network_idsocial_network`, `formation_idformation`, `formation_cours_idcours`),
  INDEX `fk_student_diplome_idx` (`diplome_iddiplome` ASC) VISIBLE,
  INDEX `fk_student_social_network1_idx` (`social_network_idsocial_network` ASC) VISIBLE,
  INDEX `fk_student_formation1_idx` (`formation_idformation` ASC, `formation_cours_idcours` ASC) VISIBLE,
  CONSTRAINT `fk_student_diplome`
    FOREIGN KEY (`diplome_iddiplome`)
    REFERENCES `mydb`.`diplome` (`iddiplome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_social_network1`
    FOREIGN KEY (`social_network_idsocial_network`)
    REFERENCES `mydb`.`social_network` (`idsocial_network`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_formation1`
    FOREIGN KEY (`formation_idformation` , `formation_cours_idcours`)
    REFERENCES `mydb`.`formation` (`idformation` , `cours_idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


-- -----------------------------------------------------
-- View `mydb`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view2`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
